// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzGsBYQPdf9wYcoMqouCt8xmxJzVR4qzU',
    appId: '1:365841116421:web:5fcea97147fa03a0751b6c',
    messagingSenderId: '365841116421',
    projectId: 'crud-10b67',
    authDomain: 'crud-10b67.firebaseapp.com',
    storageBucket: 'crud-10b67.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTB3ZydwUzRzttB3Ir0pVqeUsTsptJZS8',
    appId: '1:365841116421:android:082bf766d2f0641f751b6c',
    messagingSenderId: '365841116421',
    projectId: 'crud-10b67',
    storageBucket: 'crud-10b67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUDHnXHl2YapG3PlVCNlRe87HWmb_q0-k',
    appId: '1:365841116421:ios:bc01ba15881e51fa751b6c',
    messagingSenderId: '365841116421',
    projectId: 'crud-10b67',
    storageBucket: 'crud-10b67.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUDHnXHl2YapG3PlVCNlRe87HWmb_q0-k',
    appId: '1:365841116421:ios:bc01ba15881e51fa751b6c',
    messagingSenderId: '365841116421',
    projectId: 'crud-10b67',
    storageBucket: 'crud-10b67.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzGsBYQPdf9wYcoMqouCt8xmxJzVR4qzU',
    appId: '1:365841116421:web:3597c9baa8e7f41f751b6c',
    messagingSenderId: '365841116421',
    projectId: 'crud-10b67',
    authDomain: 'crud-10b67.firebaseapp.com',
    storageBucket: 'crud-10b67.firebasestorage.app',
  );
}